# $ conda env create --file environment.yml

name: flicker

dependencies:
  - python=2.7
  - pyserial
  - numpy
  - scipy
  - pyqtgraph
  - conda-forge:python-sounddevice

  # for development
  - ipython
  - matplotlib