# i/o
# serial_name: /dev/cu.usbmodem52417201
serial_name: /dev/cu.usbmodem53254001
data_fname: ../data/data.csv
log_fname: ../data/data.log

# for conversion of input to volts
max_analog_volts: 3.3
analog_read_resolution: 13 # unique to teensy

# flick detection
internal_sampling_rate_hz: 100 # Hz
moving_average_secs: 0.05 # secs
psd_calc_window_secs: 0.1 # secs
target_freq_index: 1 # the second lowest frequency recorded
detection_threshold_up: 0.6
detection_threshold_down: 0.4
data_buffer_len: 1000 # n data points to keep in buffer
lrlr_window_secs: 2 # secs that n_flicks must occur within
n_peaks_for_flick_detection: 4 # n flicks that must occur within lrlr_timerange for detection 